---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```

## Load in the FAS Litters Data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## `select`

Choose some columns and not others.

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```

```{r}
select(litters_df, -litter_number)
```

Renaming columns ...

```{r}
select(litters_df, GROUP = group, LITTer_NUmBer = litter_number)
```

```{r}
rename(litters_df, GROUP = group, LITTer_NUmBer = litter_number)
```

Select helpers

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```

```{r}
relocate(litters_df, litter_number)
```

## `filter`

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20))
filter(litters_df, gd_of_birth != 20)
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Con7")
```

```{r}
filter(litters_df, group %in% c("Con7", "Mod8"))
## filter rows that have either group Con7 or Mod 8
## challenging part of filter is knowing what to write down in order to keep the data you want and have logical commands to get what you want.
```

## `mutate`

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)
```

```{r}
mutate(litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))
```


## `arrange`

```{r}
arrange(litters_df, pups_born_alive)
arrange(litters_df, pups_born_alive, gd0_weight)
```

## `%>%`

```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_data_selected = select(litters_clean_name, -pups_survive)
litters_mutated = mutate(litters_data_selected, wt_gain = gd18_weight - gd0_weight)
litters_without_missing = drop_na(litters_mutated, gd0_weight)
```

USE THE PIPE OPERATOR INSTEAD

```{r}
litters_df = 
  read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(wt_gain = gd18_weight - gd0_weight) %>% 
  drop_na(gd0_weight)
```

## Learning Assessment #1 - select

```{r}
pups_df = 
  read_csv("./data/FAS_pups.csv") %>%
  janitor::clean_names() %>% 
  select(litter_number, sex, pd_ears)
```

## Learning Assessment #2 - filter

```{r}
pups_df =
  read_csv("./data/FAS_pups.csv") %>%
  janitor::clean_names() %>% 
  filter(sex == 1)
```

```{r}
pups_df =
  read_csv("./data/FAS_pups.csv") %>%
  janitor::clean_names() %>% 
  filter(pd_walk < 11, sex == 2)
```

## Learning Assessment #3 - mutate

```{r}
pups_df =
  read_csv("./data/FAS_pups.csv") %>%
  janitor::clean_names() %>% 
  mutate(pd_pivot_7 = pd_pivot - 7)
```

```{r}
pups_df =
  read_csv("./data/FAS_pups.csv") %>%
  janitor::clean_names() %>% 
  mutate(pd_sum = pd_ears + pd_eyes + pd_pivot + pd_walk)
```

## Learning Assessment #4 - %>% 

```{r}
pups_df =
  read_csv("./data/FAS_pups.csv") %>%
  janitor::clean_names() %>% 
  filter(sex == 1) %>% 
  select(-pd_ears) %>% 
  mutate(pd_pivot_7 = pd_pivot >= 7)
```

